### PR TITLE
missing cordova.js file

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
Tested activity with Sugar0.116 , the activity wasn't starting showing error as-
Traceback (most recent call last):
    File "/usr/lib/python3.7/dist-packages/sugar3/activity/webactivity.py" in line 166, in _app_cheme_cb
       request.finish(Gio.File.new_for_path(path).read(None),
gi.repository.GLib.Error: g-io-error-quark: Error opening file /usr/share/sugar/activities/PhysicsJS.activity/cordova.js: No such file or directory (1)
Fixed error by adding required file.

### CODE REVIEW

**Comment by llaske** [comment]
Hmmm. The cordova.js file is not supposed to be include in the activity.
It's provided by Sugarizer. See in [index.html](https://github.com/llaske/sugarizer/blob/dev/activities/PhysicsJS.activity/index.html#L24) :

`<script type="text/javascript" src="../../cordova.js"></script>`

Do you add it at the root of the activity or in `../..` ? guess it's in `/usr/share/sugar`

**Comment by Saumya-Mishra9129** [comment]
I tried adding to the root of the activity. I have no file named cordova.js in `/usr/share/sugar`. I am running on 0.116 Sugar .

**Comment by llaske** [comment]
The file doesn't exist because it's a file specific for Android/iOS devices.

When you said:
> Fixed error by adding required file.

Did you copy it into `/usr/share/sugar` ?

**Comment by Saumya-Mishra9129** [comment]
> Did you copy it into /usr/share/sugar ?


@llaske No I have copied it inside /usr/share/sugar/activities/PhysicsJS.activity ,

> File "/usr/lib/python3.7/dist-packages/sugar3/activity/webactivity.py" in line 166, in _app_cheme_cb
> request.finish(Gio.File.new_for_path(path).read(None),
> gi.repository.GLib.Error: g-io-error-quark: Error opening file /usr/share/sugar/activities/PhysicsJS.activity/cordova.js: No such file or directory (1)

As error is about not getting file there.

**Comment by llaske** [comment]
Ok, could you try to add it into `/usr/share/sugar` instead of into the activity directory.
This file is need for several activities.

**Comment by Saumya-Mishra9129** [comment]
Okay Sure.

**Comment by Saumya-Mishra9129** [comment]
Closing

**Pull request closed without merging**
